# Generated by Django 2.2.2 on 2019-06-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
    ]
