# Generated by Django 2.2.2 on 2019-07-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_auto_20190701_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
