# Generated by Django 2.2.2 on 2019-07-02 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0004_auto_20190701_1306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserDetail',
        ),
    ]
